import { ResearchPaper, Topic } from './types';

export const TOPICS: Topic[] = [
  { id: 'all', label: 'All Topics', icon: 'LayoutGrid' },
  { id: 'biology', label: 'Biology', icon: 'Microscope' },
  { id: 'physics', label: 'Physics', icon: 'Atom' },
  { id: 'ai', label: 'AI & ML', icon: 'Brain' },
  { id: 'quantum', label: 'Quantum Computing', icon: 'Cpu' },
  { id: 'medicine', label: 'Medicine', icon: 'Stethoscope' },
  { id: 'environment', label: 'Environment', icon: 'Globe' },
];

export const MOCK_PAPERS: ResearchPaper[] = [
  {
    id: '1',
    title: 'Room-Temperature Superconductivity in Nitrogen-doped Lutetium Hydride',
    author: 'Dr. Helena Vance',
    isVerified: true,
    category: 'Molecular Biology',
    summary: 'Breakthrough study showcasing stable superconductivity at 294K using LuH2.0 plus nitrogen doping, potentially revolutionizing power transmission and magnetic levitation...',
    citations: 1204,
    date: 'Oct 2023',
    categoryColor: 'bg-teal-500/10 text-teal-600',
  },
  {
    id: '2',
    title: 'Efficient Transformer Architectures for Real-Time Translation',
    author: 'Marcus Chen',
    isVerified: true,
    category: 'AI & Neural Networks',
    summary: 'A novel pruning method reducing LLM latency by 45% without compromising semantic integrity in complex multilingual datasets.',
    citations: 892,
    date: 'Jan 2024',
    categoryColor: 'bg-blue-500/10 text-blue-600',
  },
  {
    id: '3',
    title: 'Error Mitigation Strategies for Noisy Intermediate-Scale Quantum Devices',
    author: 'Dr. Sarah Al-Fayed',
    isVerified: true,
    category: 'Quantum Computing',
    summary: 'This research proposes a hybrid classical-quantum approach to error correction that reduces qubit overhead by 30% while maintaining gate fidelity.',
    citations: 456,
    date: 'Nov 2023',
    imageUrl: 'https://picsum.photos/seed/quantum/800/450',
    categoryColor: 'bg-purple-500/10 text-purple-600',
  },
  {
    id: '4',
    title: 'Desalination via Graphene Oxide Membranes: A Scalable Solution',
    author: 'Yoshihiro Tanaka',
    isVerified: true,
    category: 'Environmental Science',
    summary: 'A longitudinal study on carbon-based filtration systems demonstrating 98% salt rejection at industrial flow rates with low energy consumption.',
    citations: 2410,
    date: 'Dec 2023',
    categoryColor: 'bg-green-500/10 text-green-600',
  },
  {
    id: '5',
    title: 'New Insights into Dark Matter Distribution from JWST Deep Field Images',
    author: 'The Webb Collaboration',
    isVerified: true,
    category: 'Cosmology',
    summary: 'Analysis of gravitational lensing effects in the SMACS 0723 cluster reveals higher densities of non-baryonic matter than previously estimated by ΛCDM models.',
    citations: 5671,
    date: 'Feb 2024',
    categoryColor: 'bg-orange-500/10 text-orange-600',
  },
];
